function [fitResults, GOF] = matlab_Curve_Fit_Tool(i, dataToFit)

% matlab generated function to fit a curve to given data set (data_to_fit).
%
%  Data for 'cftool_1' fit:
%      X Input : i
%      Y Output: data_to_fit
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Aug-2017 14:21:58


%% Fit: 'cftool_1'.
[xData, yData]=prepareCurveData(i,dataToFit);

% Set up fittype and options.
ft=fittype('gauss1');
opts=fitoptions('Method','NonlinearLeastSquares');
opts.Display='Off';
opts.Display='Off';
opts.Lower=[.1 25 3]; % these values optimised for biol dataset 
opts.StartPoint=[2.73815143712226 1 24.0038248449245];
opts.Upper=[Inf 45 15]; % amplitude, freq, width

% Fit model to data.
[fitResult, GOF]=fit(xData, yData, ft, opts);

% % Plot fit with data.
% figure('Name','cftool_1');
% h=plot(fitresult,xData,yData);
% legend(h,'data_to_fit vs. i', 'cftool_1', 'Location', 'NorthEast' );
% % Label axes
% xlabel i
% ylabel data_to_fit
% grid on
% 

